POST http://localhost:3001/api/trails
Content-Type: application/json

{
  "name": "Some Trail",
  "description": "Coolest trail ever.",
  "gpxUrl": "test.gpx",
  "distance_km": 5.4,
  "elevation_gain_m": 210
}