POST http://localhost:3001/api/trails
Content-Type: application/json

{
  "name": "Some Trail",
  "description": "Coolest trail ever.",
  "distance_km": 5.4,
  "geojson": {
    "type": "Feature",
    "geometry": {
      "type": "LineString",
      "coordinates": [
        [24.9384, 60.1699],
        [24.9391, 60.1703]
      ]
    },
    "properties": {}
  }
}